micronaut:
  application:
    name: demo

r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: H2
      url: r2dbc:h2:mem:///testdb;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
netty:
  default:
    allocator:
      max-order: 3


---
#tag::static-resources[]
micronaut:
  router:
    static-resources: # <1>
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
#end::static-resources[]